PortalBranchNav/ViewModels/RealisasiKinerjaDPK_ViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PortalBranchNav.ViewModels
{
    public class RealisasiKinerjaDPK_ViewModels
    {
        public Int64 Number { get; set; }
        public int Id { get; set; }
        public string KodeUnit { get; set; }
        public string NamaUnit { get; set; }
        public decimal? RealisasiTabungan { get; set; }
        public decimal? RealiasiGiro { get; set; }
        public decimal? RealisasiDeposito { get; set; }
        public string Periode { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? UpdatedTime { get; set; }
        public DateTime? DeletedTime { get; set; }
        public int? CreatedById { get; set; }
        public int? UpdatedById { get; set; }
        public int? DeletedById { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
    }
}

PortalBranchNav/Controllers/RealisasiKinerjaDPKController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Transactions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using PortalBranchNav.Component;
using PortalBranchNav.Models.dbBranchNav;
using PortalBranchNav.ViewModels;

namespace PortalBranchNav.Controllers
{
    public class RealisasiKinerjaDPKController : Controller
    {
        private readonly dbBranchNavContext _context;
        private readonly IConfiguration _configuration;
        private readonly LastSessionLog lastSession;
        private readonly AccessSecurity accessSecurity;
        private IHostingEnvironment _env;

        public RealisasiKinerjaDPKController(IHostingEnvironment env, IConfiguration config, dbBranchNavContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _configuration = config;
            lastSession = new LastSessionLog(accessor, context, config);
            accessSecurity = new AccessSecurity(accessor, context, config);
            _env = env;
        }

        public IActionResult Index()
        {
            if (!lastSession.Update())
            {
                return RedirectToAction("Login", "Login", new { a = true });
            }

            var location = new Uri($"{Request.Scheme}://{Request.Host}{Request.Path}");
            string Path = location.AbsolutePath;

            if (!accessSecurity.IsGetAccess(".." + Path))
            {
                return RedirectToAction("NotAccess", "Error");
            }

            ViewBag.CurrentPath = Path;

            return View();
        }

        #region LoadData
        [HttpPost]
        public IActionResult LoadData()
        {
            if (!lastSession.Update())
            {
                return RedirectToAction("Login", "Login", new { a = true });
            }

            try
            {
                var dict = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());

                var draw = dict["draw"];

                //Untuk mengetahui info paging dari datatable
                var start = dict["start"];
                var length = dict["length"];

                //Server side datatable hanya support untuk mendapatkan data mulai ke berapa, untuk mengirim row ke berapa
                //Kita perlu membuat logika sendiri
                var pageNumber = (int.Parse(start) / int.Parse(length)) + 1;

                //Untuk mengetahui info order column datatable
                var sortColumn = dict["columns[" + dict["order[0][column]"] + "][data]"];
                var sortColumnDir = dict["order[0][dir]"];
                var PeriodeSearchParam = dict["columns[1][search][value]"];
                var KodeUnitSearchParam = dict["columns[2][search][value]"];
                var NamaUnitSearchParam = dict["columns[3][search][value]"];
                var KodePosSearchParam = dict["columns[4][search][value]"];

                //Untuk mengetahui info jumlah page dan total skip data
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                var data = new DataTableViewModel();

                //connect to API
                var url = GetConfig.AppSetting["baseApi"] + GetConfig.AppSetting["urlapi:DataRealisasi:getDPK"];
                (bool resultApi, string result) = RequestToAPI.PostRequestToWebApi(
                    url,
                    new
                    {
                        pageNumber = pageNumber,
                        pageSize = pageSize,
                        sortColumn = sortColumn,
                        sortColumnDir = sortColumnDir,
                        kodeUnit = String.IsNullOrEmpty(KodeUnitSearchParam) ? null : KodeUnitSearchParam,
                        namaUnit = String.IsNullOrEmpty(NamaUnitSearchParam) ? null : NamaUnitSearchParam,
                        periode = String.IsNullOrEmpty(PeriodeSearchParam) ? null : PeriodeSearchParam
                    },
                    HttpContext.Session.GetString(SessionConstan.jwt_Token));
                if (resultApi && !string.IsNullOrEmpty(result))
                {
                    data = JsonConvert.DeserializeObject<DataTableViewModel>(result);
                }
                return Json(
                    new
                    {
                        draw = draw,
                        recordsFiltered = data.data == null ? 0 : data.data.recordTotals,
                        recordsTotal = data.data == null ? 0 : data.data.recordTotals,
                        data = data.data == null ? new List<object>() : data.data.data == null ? new List<object>() : data.data.data
                    }
                );
            }
            catch (Exception Ex)
            {
                throw;
            }
        }
        #endregion

        #region Import File
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ImportFile(ImportFile_ViewModels model)
        {
            if (!lastSession.Update())
            {
                return RedirectToAction("Login", "Account");
            }

            try
            {
                var url = GetConfig.AppSetting["baseApi"] + GetConfig.AppSetting["urlapi:DataRealisasi:uploadDPK"];
                (bool resultApi, string result) = RequestToAPI.PostFormDataToWebApi(url, model, HttpContext.Session.GetString(SessionConstan.jwt_Token));
                if (resultApi && !string.IsNullOrEmpty(result))
                {
                    var data = JsonConvert.DeserializeObject<ServiceResult<object>>(result);
                    if (data.Code == 1)
                        return Content("");
                    else
                        return Content(data.Code + ": " + data.Message);
                }
                return Content(result);
            }
            catch (Exception Ex)
            {
                return Content(GetConfig.AppSetting["AppSettings:SistemError"]);
            }
        }
        #endregion

        #region Get Templates
        public FileStreamResult GetTemplate()
        {
            string fileName = GetConfig.AppSetting["templateUpload:RealisasiDPK"];
            if (string.IsNullOrWhiteSpace(_env.WebRootPath))
            {
                _env.WebRootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
            }
            var webRoot = _env.WebRootPath;
            string Folder = Path.Combine(webRoot, "templates");
            string file = System.IO.Path.Combine(Folder, fileName);
            FileStream fs = new FileStream(file, FileMode.Open, FileAccess.Read);
            return File(fs, "application/vnd.ms-excel", fileName);
        }
        #endregion
    }
}

PortalBranchNav/Views/RealisasiKinerjaDPK/Index - Copy.cshtml
@{
    ViewData["Title"] = "Data BRO";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    <link href="~/plugin/air-datepicker-master/dist/css/datepicker.css" rel="stylesheet" />
    <link href="@Url.Content("~/plugin/DataTables-1.10.20/media/css/datatables.min.css")" rel="stylesheet" />
    @*<link href="@Url.Content("~/plugin/DataTables-1.10.20/media/css/responsive.dataTables.min.css")" rel="stylesheet" />*@
    <link href="~/plugin/select2/dist/css/select2.min.css" rel="stylesheet" />
    <link href="~/plugin/dropify-master/dist/css/dropify.min.css" rel="stylesheet" />

    <style>
        .dataTables_wrapper {
            zoom: 0.9 !important;
        }

        table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > td:first-child:before, table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > th:first-child:before {
            background-color: #3f6ad8;
        }

        .select2-container .select2-selection--single {
            height: 35px;
        }

        .select2-container--default .select2-selection--single .select2-selection__rendered {
            padding-top: 5px;
            color: #495057;
            /*border: 1px solid #ced4da;*/
        }

        .input-group {
            margin-bottom: 5px;
        }

        select[name=Table_length] {
            height: 35px;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: white;
            border: 1px solid teal;
            border-radius: 4px;
            cursor: default;
            float: left;
            margin-right: 5px;
            margin-top: 5px;
            padding: 0 5px;
            height: 22px;
        }

        div.dataTables_wrapper {
            max-width: 1100px;
            width: auto;
            margin: 0 auto;
        }
    </style>
}
<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="row">
            <h5><b>Data Sewa ATM</b></h5>
        </div>
        <hr />
        <div id="DivContentBody">
            <div class="row">
                <div class="col-lg-3">
                    <center>
                        <button class="mb-3 mr-3 btn btn-success btn-sm btn-block" style="align-content: center;margin-left: 3%;
                    z-index: 1;width:95%" id="btnShowParameterSearch" onclick="ShowParameterSearch('btnShowParameterSearch','btnHideParameterSearch','cardParameterSearch')">
                            Tampilkan Parameter Pencarian
                        </button>
                        <button class="mb-3 mr-3 btn btn-success btn-sm btn-block" style="align-content: center;margin-left: 3%;
                    z-index: 1;display:none;width:95%;" id="btnHideParameterSearch" onclick="HideParameterSearch('btnShowParameterSearch','btnHideParameterSearch','cardParameterSearch')">
                            Sembunyikan Parameter Pencarian
                        </button>
                    </center>
                </div>
                <div class="col-lg-12">
                    <div class="main-card mb-3 card" style="display:none" id="cardParameterSearch">

                        <div class="card-body">

                            <form class="">
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="position-relative form-group">
                                            <label class="">Kode Outlet</label>
                                            <input name="city" id="txtKodeSearchParam" type="text" class="form-control" placeholder="Masukkan Kode">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="position-relative form-group">
                                            <label class="">Nama</label>
                                            <input name="city" id="txtNamaSearchParam" type="text" class="form-control" placeholder="Masukkan Nama">
                                        </div>
                                    </div>

                                </div>
                                <a href="javascript:void(0)" class="mt-2 btn btn-success pull-right" style="margin-left:10px;" id="BtnSearch">Cari</a>
                                <a href="javascript:void(0)" class="mt-2 btn btn-danger pull-right" id="BtnClearSearch">Bersihkan</a>

                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row" style="padding-top:20px;">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <a href="javascript:void(0)" class="mt-2 btn btn-success" style="margin-left:10px;" onclick="Create()">Tambah Data</a>
                            <a href="javascript:void(0)" class="mt-2 btn btn-success" style="margin-left:10px;" onclick="Import()">Import Data Sewa ATM</a>
                            <div class="row">
                                <table id="Table" class="display nowrap" style="max-width:98%;overflow-x: auto;position: sticky;">
                                    <thead class="border">
                                        <tr class="border">
                                            <th style="max-width:25px">No</th>
                                            <th style="max-width:13%">Aksi</th>
                                            <th><center>Wilayah</center></th>
                                            <th><center>Kode Unit</center></th>
                                            <th><center>Nama Unit</center></th>
                                            <th><center>ID ATM</center></th>
                                            <th><center>Tipe ATM</center></th>
                                            <th><center>Tahun Deployment</center></th>
                                            <th><center>Alamat</center></th>
                                            <th><center>Kode Pos</center></th>
                                            <th><center>Tanggal Aktiviasi</center></th>
                                            <th><center>Tanggal Mulai Sewa</center></th>
                                            <th><center>Tanggal Akhir Sewa</center></th>
                                            <th><center>Harga Total Sewa</center></th>
                                            <th><center>Latitude</center></th>
                                            <th><center>Longitude</center></th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="DivFormBody">
        </div>
    </div>
</div>




@section scripts{
    <script src="~/plugin/air-datepicker-master/dist/js/datepicker.min.js"></script>
    <script src="@Url.Content("~/plugin/DataTables-1.10.20/media/js/jquery.dataTables.min.js")"></script>
    @*<script src="@Url.Content("~/plugin/DataTables-1.10.20/media/js/dataTables.responsive.min.js")"></script>*@
    <script src="~/plugin/select2/dist/js/select2.min.js"></script>
    <script src="~/plugin/dropify-master/dist/js/dropify.min.js"></script>

    @Html.Partial("_Script")

}

PortalBranchNav/Views/RealisasiKinerjaDPK/Index.cshtml
@{ ViewData["Title"] = "Realisasi Kinerja Kredit";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

@section styles{
    <link href="~/plugin/air-datepicker-master/dist/css/datepicker.css" rel="stylesheet" />
    <link href="@Url.Content("~/plugin/DataTables-1.10.20/media/css/datatables.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/plugin/DataTables-1.10.20/media/css/responsive.dataTables.min.css")" rel="stylesheet" />
    <link href="~/plugin/select2/dist/css/select2.min.css" rel="stylesheet" />
    <link href="~/plugin/dropify-master/dist/css/dropify.min.css" rel="stylesheet" />
    <style>
        .dataTables_wrapper {
            zoom: 0.9 !important;
        }

        table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > td:first-child:before, table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > th:first-child:before {
            background-color: #3f6ad8;
        }

        .select2-container .select2-selection--single {
            height: 35px;
        }

        .select2-container--default .select2-selection--single .select2-selection__rendered {
            padding-top: 5px;
            color: #495057;
            /*border: 1px solid #ced4da;*/
        }

        .input-group {
            margin-bottom: 5px;
        }

        select[name=Table_length] {
            height: 35px;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: white;
            border: 1px solid teal;
            border-radius: 4px;
            cursor: default;
            float: left;
            margin-right: 5px;
            margin-top: 5px;
            padding: 0 5px;
            height: 22px;
        }

        .dataTables_wrapper {
            max-width: 1050px;
        }
    </style>
}
<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="pe-7s-back-2 icon-gradient bg-mean-fruit">
                        </i>
                    </div>
                    <div>
                        Data Realisasi Kinerja DPK
                        <div class="page-title-subheading">
                            Manajemen Data Realisasi Kinerja DPK
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="DivContentBody">
            <div class="row">

                <div class="col-lg-12">
                    <div class="main-card mb-3 card" id="cardParameterSearch">
                        <div class="card-body">
                            <div class="col-md-12">
                                <form id="FormImport">
                                    @Html.AntiForgeryToken()
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="position-relative form-group">
                                                <label class="">Periode Penilaian<span class="labelMandatory">*</span></label>
                                                <div class="input-group">
                                                    <div class="input-group-prepend datepicker-trigger" id="Priode" name="Priode" data-date-format="dd/mm/yyyy">
                                                        <div class="input-group-text">
                                                            <i class="fa fa-calendar-alt"></i>
                                                        </div>
                                                    </div>
                                                    <input type="text" id="PeriodeImportData" name="PeriodeImportData" class="datepicker-here form-control" , autocomplete="off" />
                                                </div>
                                            </div>
                                            <input type="text" id="PeriodeBulanTahun" name="PeriodeBulanTahun" style="display:none" class="form-control" , autocomplete="off" />
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="position-relative form-group">
                                                <label class="">Kode Unit</label>
                                                <input id="txtKodeSearchParam" type="text" class="form-control" placeholder="Masukkan Kode Unit">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="position-relative form-group">
                                                <label class="">Nama Unit</label>
                                                <input id="txtNamaSearchParam" type="text" class="form-control" placeholder="Masukkan Nama Unit">
                                            </div>
                                        </div>

                                    </div>
                                    <div id="DivImportData" style="display:none">
                                        <p>Import Data</p>
                                        <p>*) Untuk proses import data, Anda harus memilih periode terlebih dahulu!</p>
                                        <p>only allow file .csv, .xlx, .xlxs</p>
                                        <p>for template excel can be download in <a href="@Url.Action("GetTemplate","RealisasiKinerjaDPK")">here</a><br /></p>
                                        <div style="margin-bottom:15px;">
                                            <input type="file" id="file" name="file" class="dropify" />
                                        </div>
                                        <a href="javascript:void(0)" class="btn btn-success btn-block" id="btnImportData">Import Data Realisasi Kinerja DPK</a>
                                    </div>

                                </form>

                            </div>
                            <hr />
                            <a href="javascript:void(0)" class="mt-2 btn btn-success pull-right" style="margin-left:10px;" id="BtnSearchParam">Cari</a>
                            <a href="javascript:void(0)" class="mt-2 btn btn-danger pull-right" id="BtnClearSearchParam">Bersihkan</a>

                            <a href="javascript:void(0)" class="mt-2 btn btn-success" id="BtnShowImportData" style="margin-left:10px;" onclick="ShowParameterSearch('BtnShowImportData','BtnHideImportData','DivImportData')">Import Data Realisasi Kinerja DPK</a>
                            <a href="javascript:void(0)" class="mt-2 btn btn-success" id="BtnHideImportData" style="margin-left:10px;display:none;" onclick="HideParameterSearch('BtnShowImportData','BtnHideImportData','DivImportData')">Hide Form Input</a>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row" style="padding-top:20px;">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="headerSearch">
                            Data Realisasi Kinerja DPK
                        </div>
                        <div class="card-body">
                            <table id="Table" class="display nowrap" style="width:100%">
                                <thead>
                                    <tr>
                                        <th style="max-width:25px">No</th>
                                        <th></th>
                                        <th>Kode Unit</th>
                                        <th>Nama Unit </th>
                                        <th>Periode</th>
                                        <th>Realisasi Tabungan</th>
                                        <th>Realisasi Giro</th>
                                        <th>Realisasi Deposito</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="DivFormBody">
        </div>
    </div>
</div>




@section scripts{
    <script src="~/plugin/air-datepicker-master/dist/js/datepicker.min.js"></script>
    <script src="@Url.Content("~/plugin/DataTables-1.10.20/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/plugin/DataTables-1.10.20/media/js/dataTables.responsive.min.js")"></script>
    <script src="~/plugin/select2/dist/js/select2.min.js"></script>
    <script src="~/plugin/dropify-master/dist/js/dropify.min.js"></script>
    @Html.Partial("_Script")

}

PortalBranchNav/Views/RealisasiKinerjaDPK/_Create.cshtml
@model PortalBranchNav.Models.dbBranchNav.TblMasterClient

<div class="row" style="padding-top:20px;">
    <div class="col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-body">
                <form id="FormData" style="padding-top:20px;">
                    @Html.AntiForgeryToken()
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-form-label">Type Client <span class="labelMandatory">*</span></label>
                        <div class="col-md-9">
                            <div class="input-group">
                                <select class="js-example-placeholder-multiple js-states form-control" id="TypeClientId" name="TypeClientId" style="width:90%;"></select>
                                <a href="javascript:void(0)" class="btn btn-danger" onclick="ClearDropdown('TypeClientId')"><i class="fa fa-times"></i> Clear</a>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-form-label">Kode</label>
                        <div class="col-md-9">
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.Kode, new { @class = "form-control", @value = "", @autocomplete = "off" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-form-label">Nama <span class="labelMandatory">*</span></label>
                        <div class="col-md-9">
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.Nama, new { @class = "form-control", @value = "", @autocomplete = "off" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-form-label">Keterangan </label>
                        <div class="col-md-9">
                            <div class="input-group">
                                @Html.TextAreaFor(m => m.Keterangan, new { @class = "form-control", @value = "", @autocomplete = "off", @rows = "4" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-form-label">Urutan Ke <span class="labelMandatory">*</span></label>
                        <div class="col-md-9">
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.OrderBy, new { @type = "number", @class = "form-control", @value = "", @autocomplete = "off" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-form-label">Status <span class="labelMandatory">*</span></label>
                        <div class="col-md-9">
                            <div class="input-group">
                                @Html.RadioButtonFor(model => model.IsActive, true, new { })&nbsp; Aktif &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.RadioButtonFor(model => model.IsActive, false, new { })&nbsp; Tidak Aktif &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" onclick="BackDraft()">Tutup</a>
                <a href="javascript:;" class="btn btn-sm btn-primary" id="BtnSubmit">Simpan</a>
            </div>
        </div>
    </div>
</div>